# Generated by Django 5.1.4 on 2025-04-07 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("duration", models.IntegerField(help_text="Duration in seconds")),
                ("call_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("follow_up", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True, null=True)),
                ("recording_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-call_time"],
            },
        ),
    ]
